spring.application.name=product-api
spring.datasource.url=jdbc:postgresql://localhost:5432/Demodb
spring.datasource.username=postgres
spring.datasource.password=Qwaszx1234@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
